development:
  adapter: mysql2
  database: afterburn_development
  username: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  database: afterburn_test
  username: root
  pool: 5
  timeout: 5000
  reconnect: true
